name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "I don't know why you say Hello!!"
      - name: Print Goodbye
        run: echo "I say Goodbye!!" 
